name = "fib"
version = "1.0.0"

[deployment]
nodes = 1

[build]
dir = "build"
entry = "fib_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "fib.wasm"
command = "npm run build:release"
